### ISSUE TITLE
question regarding "attendance"

### ISSUE THREAD

**Issue by snapdeus** [phishnet/api-v5#1]
Hello, thank you so much for your work on the API. 

I have a quick question: it seems that "attendance" is returning the phish.net users who attended, and not the actual attendance of the show? Is this correct? 

for example, i'm doing this request: "https://api.phish.net/v5/attendance/showdate/2022-09-02.json?apikey=MYAPIKEY"
and what i get in response is 3738 items where the only real difference is the username and uid. So, I'm guessing that "attendance" means phish.net users attendance?

Thanks again for your time,
snapdeus

**Comment by sethadam1** [comment]
Hi snapdeus - yes, it's not a count of show attendance, but rather phish.net users in attendance. This method is typically used by third party apps that track your attendance in order to run some sort of stats or analysis.
